/**
 * Registry seluruh section website desa.
 *
 * File ini adalah SUMBER KEBENARAN TUNGGAL untuk:
 *  - daftar rute frontend (apps/web/src/routes)
 *  - menu navigasi publik
 *  - dokumen storyboard (scripts/generate-storyboard.mjs)
 *
 * Struktur mengikuti dokumen "Laman Website Desa Bintang Ninggi I" setelah revisi
 * coretan tangan: section "Pariwisata Desa" dan "Aspirasi Warga" dibatalkan,
 * sub-item "Lambang dan maknanya", "SMP", "SMA", "Donor darah" dihapus,
 * dan "Puskesmas" diganti menjadi "Pustu".
 */

export type Phase = 1 | 2 | 3 | 4;

/** Siapa yang boleh membuka halaman ini. */
export type Access = 'publik' | 'warga' | 'perangkat';

export interface SectionItem {
  /** Label yang tampil di UI. */
  label: string;
  /** Sub-rute relatif terhadap rute section, kosong bila hanya blok di halaman yang sama. */
  path?: string;
  /** Catatan teknis / keputusan yang masih menggantung. */
  note?: string;
}

export interface Section {
  id: string;
  /** Nomor urut setelah revisi (dokumen asli 1-25, dua section dibatalkan). */
  no: number;
  /** Nomor pada dokumen tulisan tangan, untuk penelusuran balik. */
  docNo: number;
  title: string;
  route: string;
  access: Access;
  phase: Phase;
  /** Ringkasan satu kalimat untuk storyboard. */
  summary: string;
  items: SectionItem[];
  note?: string;
}

export const SECTIONS: Section[] = [
  {
    id: 'beranda',
    no: 1,
    docNo: 1,
    title: 'Beranda',
    route: '/',
    access: 'publik',
    phase: 1,
    summary:
      'Halaman muka: sambutan kepala desa, ringkasan statistik, dan pintu cepat ke semua layanan.',
    items: [
      { label: 'Sambutan Kepala Desa' },
      { label: 'Video profil desa' },
      { label: 'Berita terbaru', path: '/berita' },
      { label: 'Pengumuman', path: '/pengumuman' },
      { label: 'Agenda kegiatan', path: '/agenda' },
      { label: 'Statistik desa (penduduk, KK, UMKM, RT/RW, luas wilayah)' },
      { label: 'Cuaca', note: 'API BMKG (gratis, tanpa API key)' },
      { label: 'Jam pelayanan' },
      { label: 'Nomor darurat' },
      { label: 'Tombol cepat menuju semua layanan' },
    ],
  },
  {
    id: 'profil',
    no: 2,
    docNo: 2,
    title: 'Profil Desa',
    route: '/profil',
    access: 'publik',
    phase: 1,
    summary: 'Identitas desa, sejarah, dan seluruh lembaga yang ada di dalamnya.',
    items: [
      { label: 'Sejarah desa', path: '/sejarah' },
      { label: 'Visi & Misi', path: '/visi-misi' },
      { label: 'Struktur organisasi', path: '/struktur' },
      { label: 'Profil Kepala Desa', path: '/kepala-desa' },
      { label: 'Profil BPD', path: '/bpd' },
      { label: 'Profil LPM', path: '/lpm' },
      { label: 'Karang Taruna', path: '/karang-taruna' },
      { label: 'PKK', path: '/pkk' },
      { label: 'BumDes', path: '/bumdes' },
      { label: 'RT/RW', path: '/rt-rw' },
      { label: 'Perangkat Desa', path: '/perangkat' },
      { label: 'Prestasi desa', path: '/prestasi' },
      { label: 'Potensi desa', path: '/potensi' },
    ],
    note: 'Sub-item "Lambang dan maknanya" dicoret pada dokumen — tidak dibuat.',
  },
  {
    id: 'pemerintahan',
    no: 3,
    docNo: 3,
    title: 'Pemerintahan Desa',
    route: '/pemerintahan',
    access: 'publik',
    phase: 1,
    summary: 'Perangkat desa beserta tugasnya dan seluruh dokumen regulasi & perencanaan.',
    items: [
      { label: 'Perangkat desa', path: '/perangkat' },
      { label: 'Tugas masing-masing perangkat', path: '/tugas' },
      { label: 'Peraturan Desa', path: '/perdes' },
      { label: 'Peraturan Kepala Desa', path: '/perkades' },
      { label: 'SK Kepala Desa', path: '/sk-kades' },
      { label: 'RPJMDes', path: '/rpjmdes' },
      { label: 'RKPDes', path: '/rkpdes' },
      { label: 'APBDes', path: '/apbdes' },
      { label: 'Laporan Realisasi APBDes', path: '/realisasi-apbdes' },
    ],
    note: 'Sub-item "Dokumen PPID" ditandai pada dokumen — dipindahkan ke section PPID (no. 22) agar tidak duplikat.',
  },
  {
    id: 'layanan',
    no: 4,
    docNo: 4,
    title: 'Pelayanan Online',
    route: '/layanan',
    access: 'publik',
    phase: 1,
    summary:
      'Warga login lalu mengajukan surat; berkas terbit dengan QR Code verifikasi dan tanda tangan elektronik.',
    items: [
      { label: 'Surat Domisili' },
      { label: 'Surat Keterangan Usaha' },
      { label: 'Surat Tidak Mampu' },
      { label: 'Surat Kelahiran' },
      { label: 'Surat Kematian' },
      { label: 'Surat Pindah' },
      { label: 'Surat Pengantar Nikah' },
      { label: 'Surat Kehilangan' },
      { label: 'Surat Ahli Waris' },
      { label: 'Surat Keterangan Belum Menikah' },
      { label: 'Surat Keterangan Penghasilan' },
      { label: 'Surat Pengantar SKCK' },
      { label: 'Surat Izin Keramaian' },
      { label: 'Surat lainnya' },
      {
        label: 'Status pengajuan: Diproses / Disetujui / Ditolak / Siap diambil',
        path: '/status',
      },
      {
        label: 'Verifikasi dokumen via QR Code',
        path: '/verifikasi/:kode',
        note: 'Halaman publik tanpa login — memindai QR pada surat cetak.',
      },
    ],
    note: 'Verifikasi memakai QR mandiri milik desa (hash SHA-256 isi PDF), bukan PSrE tersertifikasi. Surat tetap ditandatangani basah; QR membuktikan lembar yang dipegang benar terbit dari sistem dan isinya belum diubah.',
  },
  {
    id: 'kependudukan',
    no: 5,
    docNo: 5,
    title: 'Data Kependudukan',
    route: '/kependudukan',
    access: 'publik',
    phase: 1,
    summary: 'Dashboard statistik agregat penduduk — angka saja, tanpa data pribadi.',
    items: [
      { label: 'Jumlah Penduduk' },
      { label: 'Jumlah KK' },
      { label: 'Laki-laki' },
      { label: 'Perempuan' },
      { label: 'Usia' },
      { label: 'Pendidikan' },
      { label: 'Agama' },
      { label: 'Pekerjaan' },
      { label: 'Penyandang Disabilitas' },
      { label: 'Balita' },
      { label: 'Lansia' },
      { label: 'Pendatang' },
      { label: 'Kelahiran' },
      { label: 'Kematian' },
      { label: 'Mutasi' },
    ],
    note: 'Wajib agregat. Data individu hanya di Dashboard Perangkat dengan audit log (UU PDP 27/2022).',
  },
  {
    id: 'keuangan',
    no: 6,
    docNo: 6,
    title: 'Transparansi Keuangan',
    route: '/keuangan',
    access: 'publik',
    phase: 2,
    summary: 'Rincian dan grafik penggunaan anggaran desa per tahun.',
    items: [
      { label: 'APBDes' },
      { label: 'Pendapatan' },
      { label: 'Belanja' },
      { label: 'Realisasi Anggaran' },
      { label: 'Dana Desa' },
      { label: 'Dana Bagi Hasil' },
      { label: 'Grafik penggunaan anggaran' },
      { label: 'Proyek yang sedang berjalan' },
    ],
  },
  {
    id: 'pembangunan',
    no: 7,
    docNo: 7,
    title: 'Pembangunan Desa',
    route: '/pembangunan',
    access: 'publik',
    phase: 2,
    summary: 'Daftar proyek desa lengkap dengan progres, foto, dan titik lokasi di peta.',
    items: [
      { label: 'Daftar proyek' },
      { label: 'Lokasi proyek' },
      { label: 'Nilai proyek' },
      { label: 'Sumber dana' },
      { label: 'Foto progres' },
      { label: 'Persentase pekerjaan' },
      { label: 'Timeline' },
      { label: 'Kontraktor' },
      { label: 'Pengawas' },
      { label: 'Peta lokasi', note: 'Leaflet + OpenStreetMap' },
      { label: 'Proyek selesai' },
      { label: 'Dokumen laporan' },
    ],
  },
  {
    id: 'pengaduan',
    no: 8,
    docNo: 8,
    title: 'Pengaduan Masyarakat',
    route: '/pengaduan',
    access: 'publik',
    phase: 2,
    summary: 'Warga melaporkan masalah dengan foto dan titik GPS, lalu memantau statusnya.',
    items: [
      { label: 'Jalan rusak' },
      { label: 'Lampu mati' },
      { label: 'Sampah' },
      { label: 'Banjir' },
      { label: 'Pelayanan' },
      { label: 'Konflik sosial' },
      { label: 'Kebakaran' },
      { label: 'Infrastruktur' },
      { label: 'Unggah foto + lokasi GPS', path: '/buat' },
      { label: 'Status laporan', path: '/status' },
    ],
  },
  {
    id: 'umkm',
    no: 9,
    docNo: 9,
    title: 'UMKM Desa',
    route: '/umkm',
    access: 'publik',
    phase: 3,
    summary: 'Marketplace produk warga dengan keranjang, rating, dan pembayaran QRIS.',
    items: [
      { label: 'Produk makanan' },
      { label: 'Kerajinan' },
      { label: 'Pertanian' },
      { label: 'Peternakan' },
      { label: 'Perikanan' },
      { label: 'Jasa' },
      { label: 'Keranjang belanja', path: '/keranjang' },
      { label: 'WhatsApp penjual' },
      { label: 'Rating' },
      {
        label: 'Pembayaran QRIS (manual)',
        note: 'Tiap UMKM memasang QRIS sendiri. Pembeli mengunggah bukti bayar, penjual yang memverifikasi — tanpa payment gateway, tanpa desa memegang uang warga.',
      },
      { label: 'Pesanan saya', path: '/pesanan' },
    ],
  },
  {
    id: 'bumdes',
    no: 10,
    docNo: 10,
    title: 'BumDes',
    route: '/bumdes',
    access: 'publik',
    phase: 3,
    summary: 'Profil badan usaha milik desa, unit usaha, produk, dan laporannya.',
    items: [
      { label: 'Profil' },
      { label: 'Unit usaha' },
      { label: 'Laporan' },
      { label: 'Produk' },
      { label: 'Penyewaan alat' },
      { label: 'Investasi desa' },
    ],
  },
  {
    id: 'pendidikan',
    no: 11,
    docNo: 12,
    title: 'Pendidikan',
    route: '/pendidikan',
    access: 'publik',
    phase: 4,
    summary: 'Fasilitas pendidikan yang ada di desa beserta program beasiswa.',
    items: [
      { label: 'PAUD' },
      { label: 'SD' },
      { label: 'Beasiswa' },
      { label: 'Perpustakaan Desa' },
      { label: 'Jadwal belajar' },
      { label: 'Kursus' },
    ],
    note: 'Sub-item "SMP" dan "SMA" dicoret pada dokumen — tidak dibuat.',
  },
  {
    id: 'kesehatan',
    no: 12,
    docNo: 13,
    title: 'Kesehatan',
    route: '/kesehatan',
    access: 'publik',
    phase: 4,
    summary: 'Layanan kesehatan desa: Posyandu, Pustu, ambulans, dan program ibu-anak.',
    items: [
      { label: 'Posyandu' },
      { label: 'Jadwal imunisasi' },
      { label: 'Pustu', note: 'Koreksi tulisan tangan: "Puskesmas" diganti menjadi "Pustu".' },
      { label: 'Ambulans' },
      { label: 'Stunting' },
      { label: 'Ibu hamil' },
      { label: 'Jadwal dokter' },
    ],
    note: 'Sub-item "Donor darah" dicoret pada dokumen — tidak dibuat.',
  },
  {
    id: 'pertanian',
    no: 13,
    docNo: 14,
    title: 'Pertanian',
    route: '/pertanian',
    access: 'publik',
    phase: 3,
    summary: 'Informasi harga komoditas, jadwal tanam, pupuk, dan penyuluhan.',
    items: [
      { label: 'Harga komoditas' },
      { label: 'Jadwal tanam' },
      { label: 'Cuaca' },
      { label: 'Pupuk' },
      { label: 'Bantuan' },
      { label: 'Penyuluhan' },
      { label: 'Alat pertanian' },
      { label: 'Irigasi' },
    ],
  },
  {
    id: 'peternakan',
    no: 14,
    docNo: 15,
    title: 'Peternakan',
    route: '/peternakan',
    access: 'publik',
    phase: 3,
    summary: 'Program vaksin ternak, informasi penyakit, bantuan bibit, dan penyuluhan.',
    items: [
      { label: 'Vaksin ternak' },
      { label: 'Penyakit' },
      { label: 'Bantuan' },
      { label: 'Bibit' },
      { label: 'Jadwal penyuluhan' },
    ],
  },
  {
    id: 'perikanan',
    no: 15,
    docNo: 16,
    title: 'Perikanan',
    route: '/perikanan',
    access: 'publik',
    phase: 3,
    summary: 'Bibit ikan, harga jual, bantuan, dan pelatihan budidaya.',
    items: [
      { label: 'Bibit ikan' },
      { label: 'Bantuan' },
      { label: 'Harga ikan' },
      { label: 'Pelatihan' },
    ],
  },
  {
    id: 'bantuan-sosial',
    no: 16,
    docNo: 17,
    title: 'Bantuan Sosial',
    route: '/bantuan-sosial',
    access: 'publik',
    phase: 3,
    summary: 'Daftar program bantuan; warga mengecek status penerima memakai NIK.',
    items: [
      { label: 'PKH' },
      { label: 'BPNT' },
      { label: 'BLT' },
      { label: 'Bantuan UMKM' },
      { label: 'Bantuan Rumah' },
      { label: 'KIP' },
      { label: 'PIP' },
      {
        label: 'Cek status penerima dengan NIK',
        path: '/cek',
        note: 'Wajib di balik login warga — jangan jadikan endpoint publik agar NIK tidak bisa dienumerasi.',
      },
    ],
  },
  {
    id: 'lowongan',
    no: 17,
    docNo: 18,
    title: 'Lowongan Kerja',
    route: '/lowongan',
    access: 'publik',
    phase: 3,
    summary: 'Papan lowongan lokal, magang, pelatihan kerja, dan rekrutmen perusahaan.',
    items: [
      { label: 'Lowongan lokal' },
      { label: 'Magang' },
      { label: 'Pelatihan kerja' },
      { label: 'Rekrutmen perusahaan' },
    ],
  },
  {
    id: 'kalender',
    no: 18,
    docNo: 19,
    title: 'Kalender Desa',
    route: '/kalender',
    access: 'publik',
    phase: 4,
    summary: 'Kalender kegiatan desa sepanjang tahun.',
    items: [
      { label: 'Musyawarah Desa' },
      { label: 'Posyandu' },
      { label: 'Gotong Royong' },
      { label: 'Festival' },
      { label: 'Hari Besar' },
      { label: 'Rapat RT' },
    ],
  },
  {
    id: 'galeri',
    no: 19,
    docNo: 20,
    title: 'Galeri',
    route: '/galeri',
    access: 'publik',
    phase: 4,
    summary: 'Dokumentasi foto, video, dan rekaman drone kegiatan desa.',
    items: [
      { label: 'Foto' },
      { label: 'Video' },
      { label: 'Drone' },
      { label: 'Dokumentasi kegiatan' },
    ],
  },
  {
    id: 'peta',
    no: 20,
    docNo: 21,
    title: 'Peta Desa Interaktif',
    route: '/peta',
    access: 'publik',
    phase: 4,
    summary: 'Peta desa dengan layer yang bisa dinyalakan per kategori fasilitas.',
    items: [
      { label: 'RT/RW' },
      { label: 'Jalan' },
      { label: 'Sungai' },
      { label: 'Sawah' },
      { label: 'Sekolah' },
      { label: 'Masjid/Gereja' },
      { label: 'Posyandu' },
      { label: 'Wisata' },
      { label: 'UMKM' },
      { label: 'Kantor Desa' },
    ],
    note: 'Leaflet + OpenStreetMap agar tanpa biaya dan tanpa API key.',
  },
  {
    id: 'download',
    no: 21,
    docNo: 23,
    title: 'Download Center',
    route: '/download',
    access: 'publik',
    phase: 2,
    summary: 'Arsip berkas yang bisa diunduh warga.',
    items: [
      { label: 'Formulir' },
      { label: 'Peraturan Desa' },
      { label: 'Surat' },
      { label: 'Proposal' },
      { label: 'Laporan' },
    ],
  },
  {
    id: 'ppid',
    no: 22,
    docNo: 24,
    title: 'PPID',
    route: '/ppid',
    access: 'publik',
    phase: 2,
    summary: 'Pejabat Pengelola Informasi dan Dokumentasi — klasifikasi informasi publik.',
    items: [
      { label: 'Informasi berkala' },
      { label: 'Informasi setiap saat' },
      { label: 'Informasi serta merta' },
      { label: 'Permohonan informasi', path: '/permohonan' },
    ],
    note: 'Menampung juga "Dokumen PPID" yang semula tercantum di section Pemerintahan Desa.',
  },
  {
    id: 'kontak',
    no: 23,
    docNo: 25,
    title: 'Kontak',
    route: '/kontak',
    access: 'publik',
    phase: 4,
    summary: 'Kanal komunikasi resmi desa.',
    items: [
      { label: 'Nomor WA Desa' },
      { label: 'Email' },
      { label: 'Maps' },
      { label: 'Facebook' },
      { label: 'Instagram' },
      { label: 'TikTok' },
      { label: 'YouTube' },
    ],
  },
];

/** Section yang dibatalkan lewat coretan tangan — disimpan agar keputusan tidak hilang. */
export const SECTIONS_DIBATALKAN = [
  {
    docNo: 11,
    title: 'Pariwisata Desa',
    alasan: 'Dicoret X besar pada dokumen (Destinasi wisata, Penginapan, Kuliner, Kalender event, Tiket online, Galeri, Virtual Tour).',
  },
  {
    docNo: 22,
    title: 'Aspirasi Warga',
    alasan: 'Dicoret X besar pada dokumen (Usulan pembangunan, Voting, Saran).',
  },
] as const;

export const DASHBOARD_PERANGKAT = {
  id: 'dashboard-perangkat',
  title: 'Dashboard Perangkat Desa',
  route: '/admin',
  access: 'perangkat' as Access,
  phase: 1 as Phase,
  summary: 'Ruang kerja perangkat desa: kelola data, setujui surat, dan perbarui konten.',
  items: [
    { label: 'Profil desa', path: '/profil-desa' },
    { label: 'Manajemen penduduk', path: '/penduduk' },
    { label: 'Manajemen surat', path: '/surat' },
    { label: 'Persetujuan surat', path: '/surat/persetujuan' },
    { label: 'Keuangan', path: '/keuangan' },
    { label: 'Pengaduan', path: '/pengaduan' },
    { label: 'Pembangunan', path: '/pembangunan' },
    { label: 'Agenda', path: '/agenda' },
    { label: 'Berita', path: '/berita' },
    { label: 'Galeri', path: '/galeri' },
    { label: 'Arsip digital', path: '/arsip' },
    { label: 'Absensi perangkat', path: '/absensi' },
    { label: 'Inventaris aset', path: '/aset' },
    { label: 'Statistik real-time', path: '/statistik' },
  ] as SectionItem[],
};

export const DASHBOARD_WARGA = {
  id: 'dashboard-warga',
  title: 'Dashboard Warga',
  route: '/warga',
  access: 'warga' as Access,
  phase: 1 as Phase,
  summary: 'Ruang pribadi warga setelah login dengan NIK.',
  items: [
    { label: 'Data pribadi', path: '/profil' },
    { label: 'Riwayat surat', path: '/surat' },
    { label: 'Status bantuan', path: '/bantuan' },
    { label: 'Pajak desa', path: '/pajak' },
    { label: 'Tagihan', path: '/tagihan' },
    { label: 'Pengaduan', path: '/pengaduan' },
    { label: 'Riwayat kegiatan', path: '/kegiatan' },
    { label: 'Sertifikat pelatihan', path: '/sertifikat' },
    { label: 'UMKM saya', path: '/umkm' },
  ] as SectionItem[],
};

export const sectionById = (id: string) => SECTIONS.find((s) => s.id === id);
export const sectionsByPhase = (phase: Phase) => SECTIONS.filter((s) => s.phase === phase);
